all:
	@make -C msgh
	@make -C cr
	@make -C eh
	@make -C init
	@make -C timer
	@make -C dbi

clean:
	@make -C msgh clean
	@make -C cr clean
	@make -C eh clean
	@make -C init clean
	@make -C timer clean
	@make -C dbi clean

